server:
  port: 8091

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/publiccode?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
#    host: 127.0.0.1
    host: 192.168.19.10
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms


        #=======redis连接池配置==============
        # Redis数据库索引（默认为0）


#        spring.redis.database=0
#        # Redis服务器地址
#        spring.redis.host=127.0.0.1
#        # Redis服务器连接端口
#        spring.redis.port=6379
#        # Redis服务器连接密码（默认为空）
#        spring.redis.password=
#        # 连接池最大连接数（使用负值表示没有限制）
#        spring.redis.jedis.pool.max-active=20
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        spring.redis.jedis.pool.max-wait=-1
#        # 连接池中的最大空闲连接
#        spring.redis.jedis.pool.max-idle=10
#        # 连接池中的最小空闲连接
#        spring.redis.jedis.pool.min-idle=0
#        # 连接超时时间（毫秒）
#        spring.redis.timeout=0
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zh.publiccode.entity