spring:
  datasource:
    url: jdbc:mysql://192.168.3.95:3306/publiccode?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource