spring:
  datasource:
    url: jdbc:mysql://192.168.3.95:3306/publiccode?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  #配置mq
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: guest
    password: guest
    #虚拟机默认
    virtual-host: /
